### ISSUE TITLE
acmart does not export include-abstract

### ISSUE THREAD

**Issue by mfelleisen** [racket/scribble#93] opened 2017-03-22 15:22 UTC
. . . but it is in the docs.

**Comment by bennn** [comment] 2017-03-23 16:43
Similar issue: abstracts defined with `@abstract{...}` do not appear in documents.

The problem is,

> The environment `abstract` must appear before `\maketitle`

in acmart.cls. See page 15 in http://ctan.sharelatex.com/tex-archive/macros/latex/contrib/acmart/acmart.pdf

**Comment by bennn** [comment] 2018-02-12 01:16
closed by #160

**Closed by bennn** 2018-02-12 01:16 UTC
